### ISSUE TITLE
GraphQL credentials Error

### ISSUE THREAD

**Issue by Emiller00** [aspittel/giphlify#3]
So I did the tutorial close to as described. I got to the point where you first use the AWS Amplify API to add urls to the graphQL database. When I do that, in the console, I see an errror with my graphQL credentials. 

Specifically, I am getting

`script.js:27 Error: No credentials
    at GraphQLAPIClass.<anonymous> (GraphQLAPI.ts:138)
    at step (GraphQLAPI.ts:30)
    at Object.next (GraphQLAPI.ts:30)
    at fulfilled (GraphQLAPI.ts:30)
createNewGif @ script.js:27
async function (async)
createNewGif @ script.js:20`

It seems like my graphQL API doesn't have the right credentials. Is there a way of giving it credentials?

**Comment by Emiller00** [comment]
Redid the project and it works??? XD I guess I wasn't following the instructions carefully?

**Comment by aspittel** [comment]
Glad to hear it worked for you!
